// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

#ifndef PROTOBUF_INCLUDED_demo_2eproto
#define PROTOBUF_INCLUDED_demo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_demo_2eproto 

namespace protobuf_demo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_demo_2eproto
namespace CSR {
class CSTBS;
class CSTBSDefaultTypeInternal;
extern CSTBSDefaultTypeInternal _CSTBS_default_instance_;
}  // namespace CSR
namespace google {
namespace protobuf {
template<> ::CSR::CSTBS* Arena::CreateMaybeMessage<::CSR::CSTBS>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace CSR {

// ===================================================================

class CSTBS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CSR.CSTBS) */ {
 public:
  CSTBS();
  virtual ~CSTBS();

  CSTBS(const CSTBS& from);

  inline CSTBS& operator=(const CSTBS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CSTBS(CSTBS&& from) noexcept
    : CSTBS() {
    *this = ::std::move(from);
  }

  inline CSTBS& operator=(CSTBS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CSTBS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CSTBS* internal_default_instance() {
    return reinterpret_cast<const CSTBS*>(
               &_CSTBS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CSTBS* other);
  friend void swap(CSTBS& a, CSTBS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CSTBS* New() const final {
    return CreateMaybeMessage<CSTBS>(NULL);
  }

  CSTBS* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CSTBS>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CSTBS& from);
  void MergeFrom(const CSTBS& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CSTBS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string curveID = 3;
  void clear_curveid();
  static const int kCurveIDFieldNumber = 3;
  const ::std::string& curveid() const;
  void set_curveid(const ::std::string& value);
  #if LANG_CXX11
  void set_curveid(::std::string&& value);
  #endif
  void set_curveid(const char* value);
  void set_curveid(const char* value, size_t size);
  ::std::string* mutable_curveid();
  ::std::string* release_curveid();
  void set_allocated_curveid(::std::string* curveid);

  // string hashID = 4;
  void clear_hashid();
  static const int kHashIDFieldNumber = 4;
  const ::std::string& hashid() const;
  void set_hashid(const ::std::string& value);
  #if LANG_CXX11
  void set_hashid(::std::string&& value);
  #endif
  void set_hashid(const char* value);
  void set_hashid(const char* value, size_t size);
  ::std::string* mutable_hashid();
  ::std::string* release_hashid();
  void set_allocated_hashid(::std::string* hashid);

  // int64 deviceID = 1;
  void clear_deviceid();
  static const int kDeviceIDFieldNumber = 1;
  ::google::protobuf::int64 deviceid() const;
  void set_deviceid(::google::protobuf::int64 value);

  // int64 orgID = 2;
  void clear_orgid();
  static const int kOrgIDFieldNumber = 2;
  ::google::protobuf::int64 orgid() const;
  void set_orgid(::google::protobuf::int64 value);

  // int64 pubKLen = 5;
  void clear_pubklen();
  static const int kPubKLenFieldNumber = 5;
  ::google::protobuf::int64 pubklen() const;
  void set_pubklen(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:CSR.CSTBS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr curveid_;
  ::google::protobuf::internal::ArenaStringPtr hashid_;
  ::google::protobuf::int64 deviceid_;
  ::google::protobuf::int64 orgid_;
  ::google::protobuf::int64 pubklen_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_demo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CSTBS

// int64 deviceID = 1;
inline void CSTBS::clear_deviceid() {
  deviceid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CSTBS::deviceid() const {
  // @@protoc_insertion_point(field_get:CSR.CSTBS.deviceID)
  return deviceid_;
}
inline void CSTBS::set_deviceid(::google::protobuf::int64 value) {
  
  deviceid_ = value;
  // @@protoc_insertion_point(field_set:CSR.CSTBS.deviceID)
}

// int64 orgID = 2;
inline void CSTBS::clear_orgid() {
  orgid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CSTBS::orgid() const {
  // @@protoc_insertion_point(field_get:CSR.CSTBS.orgID)
  return orgid_;
}
inline void CSTBS::set_orgid(::google::protobuf::int64 value) {
  
  orgid_ = value;
  // @@protoc_insertion_point(field_set:CSR.CSTBS.orgID)
}

// string curveID = 3;
inline void CSTBS::clear_curveid() {
  curveid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSTBS::curveid() const {
  // @@protoc_insertion_point(field_get:CSR.CSTBS.curveID)
  return curveid_.GetNoArena();
}
inline void CSTBS::set_curveid(const ::std::string& value) {
  
  curveid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CSR.CSTBS.curveID)
}
#if LANG_CXX11
inline void CSTBS::set_curveid(::std::string&& value) {
  
  curveid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CSR.CSTBS.curveID)
}
#endif
inline void CSTBS::set_curveid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  curveid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CSR.CSTBS.curveID)
}
inline void CSTBS::set_curveid(const char* value, size_t size) {
  
  curveid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CSR.CSTBS.curveID)
}
inline ::std::string* CSTBS::mutable_curveid() {
  
  // @@protoc_insertion_point(field_mutable:CSR.CSTBS.curveID)
  return curveid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSTBS::release_curveid() {
  // @@protoc_insertion_point(field_release:CSR.CSTBS.curveID)
  
  return curveid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSTBS::set_allocated_curveid(::std::string* curveid) {
  if (curveid != NULL) {
    
  } else {
    
  }
  curveid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), curveid);
  // @@protoc_insertion_point(field_set_allocated:CSR.CSTBS.curveID)
}

// string hashID = 4;
inline void CSTBS::clear_hashid() {
  hashid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSTBS::hashid() const {
  // @@protoc_insertion_point(field_get:CSR.CSTBS.hashID)
  return hashid_.GetNoArena();
}
inline void CSTBS::set_hashid(const ::std::string& value) {
  
  hashid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CSR.CSTBS.hashID)
}
#if LANG_CXX11
inline void CSTBS::set_hashid(::std::string&& value) {
  
  hashid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CSR.CSTBS.hashID)
}
#endif
inline void CSTBS::set_hashid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hashid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CSR.CSTBS.hashID)
}
inline void CSTBS::set_hashid(const char* value, size_t size) {
  
  hashid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CSR.CSTBS.hashID)
}
inline ::std::string* CSTBS::mutable_hashid() {
  
  // @@protoc_insertion_point(field_mutable:CSR.CSTBS.hashID)
  return hashid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSTBS::release_hashid() {
  // @@protoc_insertion_point(field_release:CSR.CSTBS.hashID)
  
  return hashid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSTBS::set_allocated_hashid(::std::string* hashid) {
  if (hashid != NULL) {
    
  } else {
    
  }
  hashid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hashid);
  // @@protoc_insertion_point(field_set_allocated:CSR.CSTBS.hashID)
}

// int64 pubKLen = 5;
inline void CSTBS::clear_pubklen() {
  pubklen_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CSTBS::pubklen() const {
  // @@protoc_insertion_point(field_get:CSR.CSTBS.pubKLen)
  return pubklen_;
}
inline void CSTBS::set_pubklen(::google::protobuf::int64 value) {
  
  pubklen_ = value;
  // @@protoc_insertion_point(field_set:CSR.CSTBS.pubKLen)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace CSR

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_demo_2eproto
