// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csrtbs.proto

#ifndef PROTOBUF_csrtbs_2eproto__INCLUDED
#define PROTOBUF_csrtbs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace CA {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_csrtbs_2eproto();
void protobuf_AssignDesc_csrtbs_2eproto();
void protobuf_ShutdownFile_csrtbs_2eproto();

class CSTBS;

// ===================================================================

class CSTBS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CA.CSTBS) */ {
 public:
  CSTBS();
  virtual ~CSTBS();

  CSTBS(const CSTBS& from);

  inline CSTBS& operator=(const CSTBS& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CSTBS& default_instance();

  void Swap(CSTBS* other);

  // implements Message ----------------------------------------------

  inline CSTBS* New() const { return New(NULL); }

  CSTBS* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CSTBS& from);
  void MergeFrom(const CSTBS& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CSTBS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 deviceID = 1;
  void clear_deviceid();
  static const int kDeviceIDFieldNumber = 1;
  ::google::protobuf::int32 deviceid() const;
  void set_deviceid(::google::protobuf::int32 value);

  // optional int32 orgID = 2;
  void clear_orgid();
  static const int kOrgIDFieldNumber = 2;
  ::google::protobuf::int32 orgid() const;
  void set_orgid(::google::protobuf::int32 value);

  // optional string curveID = 3;
  void clear_curveid();
  static const int kCurveIDFieldNumber = 3;
  const ::std::string& curveid() const;
  void set_curveid(const ::std::string& value);
  void set_curveid(const char* value);
  void set_curveid(const char* value, size_t size);
  ::std::string* mutable_curveid();
  ::std::string* release_curveid();
  void set_allocated_curveid(::std::string* curveid);

  // optional string hashID = 4;
  void clear_hashid();
  static const int kHashIDFieldNumber = 4;
  const ::std::string& hashid() const;
  void set_hashid(const ::std::string& value);
  void set_hashid(const char* value);
  void set_hashid(const char* value, size_t size);
  ::std::string* mutable_hashid();
  ::std::string* release_hashid();
  void set_allocated_hashid(::std::string* hashid);

  // optional int32 pubKLen = 5;
  void clear_pubklen();
  static const int kPubKLenFieldNumber = 5;
  ::google::protobuf::int32 pubklen() const;
  void set_pubklen(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CA.CSTBS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 deviceid_;
  ::google::protobuf::int32 orgid_;
  ::google::protobuf::internal::ArenaStringPtr curveid_;
  ::google::protobuf::internal::ArenaStringPtr hashid_;
  ::google::protobuf::int32 pubklen_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_csrtbs_2eproto();
  friend void protobuf_AssignDesc_csrtbs_2eproto();
  friend void protobuf_ShutdownFile_csrtbs_2eproto();

  void InitAsDefaultInstance();
  static CSTBS* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CSTBS

// optional int32 deviceID = 1;
inline void CSTBS::clear_deviceid() {
  deviceid_ = 0;
}
inline ::google::protobuf::int32 CSTBS::deviceid() const {
  // @@protoc_insertion_point(field_get:CA.CSTBS.deviceID)
  return deviceid_;
}
inline void CSTBS::set_deviceid(::google::protobuf::int32 value) {
  
  deviceid_ = value;
  // @@protoc_insertion_point(field_set:CA.CSTBS.deviceID)
}

// optional int32 orgID = 2;
inline void CSTBS::clear_orgid() {
  orgid_ = 0;
}
inline ::google::protobuf::int32 CSTBS::orgid() const {
  // @@protoc_insertion_point(field_get:CA.CSTBS.orgID)
  return orgid_;
}
inline void CSTBS::set_orgid(::google::protobuf::int32 value) {
  
  orgid_ = value;
  // @@protoc_insertion_point(field_set:CA.CSTBS.orgID)
}

// optional string curveID = 3;
inline void CSTBS::clear_curveid() {
  curveid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSTBS::curveid() const {
  // @@protoc_insertion_point(field_get:CA.CSTBS.curveID)
  return curveid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSTBS::set_curveid(const ::std::string& value) {
  
  curveid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CA.CSTBS.curveID)
}
inline void CSTBS::set_curveid(const char* value) {
  
  curveid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CA.CSTBS.curveID)
}
inline void CSTBS::set_curveid(const char* value, size_t size) {
  
  curveid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CA.CSTBS.curveID)
}
inline ::std::string* CSTBS::mutable_curveid() {
  
  // @@protoc_insertion_point(field_mutable:CA.CSTBS.curveID)
  return curveid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSTBS::release_curveid() {
  // @@protoc_insertion_point(field_release:CA.CSTBS.curveID)
  
  return curveid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSTBS::set_allocated_curveid(::std::string* curveid) {
  if (curveid != NULL) {
    
  } else {
    
  }
  curveid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), curveid);
  // @@protoc_insertion_point(field_set_allocated:CA.CSTBS.curveID)
}

// optional string hashID = 4;
inline void CSTBS::clear_hashid() {
  hashid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CSTBS::hashid() const {
  // @@protoc_insertion_point(field_get:CA.CSTBS.hashID)
  return hashid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSTBS::set_hashid(const ::std::string& value) {
  
  hashid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CA.CSTBS.hashID)
}
inline void CSTBS::set_hashid(const char* value) {
  
  hashid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CA.CSTBS.hashID)
}
inline void CSTBS::set_hashid(const char* value, size_t size) {
  
  hashid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CA.CSTBS.hashID)
}
inline ::std::string* CSTBS::mutable_hashid() {
  
  // @@protoc_insertion_point(field_mutable:CA.CSTBS.hashID)
  return hashid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CSTBS::release_hashid() {
  // @@protoc_insertion_point(field_release:CA.CSTBS.hashID)
  
  return hashid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CSTBS::set_allocated_hashid(::std::string* hashid) {
  if (hashid != NULL) {
    
  } else {
    
  }
  hashid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hashid);
  // @@protoc_insertion_point(field_set_allocated:CA.CSTBS.hashID)
}

// optional int32 pubKLen = 5;
inline void CSTBS::clear_pubklen() {
  pubklen_ = 0;
}
inline ::google::protobuf::int32 CSTBS::pubklen() const {
  // @@protoc_insertion_point(field_get:CA.CSTBS.pubKLen)
  return pubklen_;
}
inline void CSTBS::set_pubklen(::google::protobuf::int32 value) {
  
  pubklen_ = value;
  // @@protoc_insertion_point(field_set:CA.CSTBS.pubKLen)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace CA

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_csrtbs_2eproto__INCLUDED
